<?php



/**
 * @file
 * Create (manually or scheduled) and restore backups of your Drupal MySQL
 * database with an option to exclude table data (e.g. cache_*)
 */

define('BACKUP_MIGRATE_VERSION', '6.x-3.x');
define('BACKUP_MIGRATE_MENU_PATH', 'admin/content/backup_migrate');
define('BACKUP_MIGRATE_MENU_DEPTH', 3);

/* Drupal Hooks */

/**
 * Implementation of hook_help().
 */
function backup_migrate_help($section, $arg) {
  $help = array(
    array(
      'body' => 
       t('Backup and Migrate makes the task of backing up your Drupal database and migrating data from one Drupal install to another easier. It provides a function to backup the entire database to file or download, and to restore from a previous backup. You can also schedule the backup operation. Compression of backup files is also supported.  The database backup files created with this module can be imported into this or any other Drupal installation with the !restorelink, or you can use a database tool such as <a href="!phpmyadminurl">phpMyAdmin</a> or the mysql command line command.',
         array(
            '!restorelink' => user_access('restore from backup') ? l(t('restore feature'), BACKUP_MIGRATE_MENU_PATH . '/restore') : t('restore feature'), 
            '!phpmyadminurl' => 'http://www.phpmyadmin.net'
          )
        )
    ),
    BACKUP_MIGRATE_MENU_PATH => array(
      'title' => t('Quick Backup Tab'),
      'body' => t('Use this form to run simple manual backups of your database. Visit the !helppage for more help using this module', 
                  array('!helppage' => l(t('help page'), 'admin/help/backup_migrate'))),
      'access arguments' => array('perform backup'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/export/advanced' => array(
      'title' => t('Advanced Backup Tab'),
      'body' => t('Use this form to run manual backups of your database with more advanced options. If you have any !profilelink saved you can load those settings. You can save any of the changes you make to these settings as a new settings profile.', 
                  array("!profilelink" => user_access('administer backup and migrate') ? l(t('settings profiles'), BACKUP_MIGRATE_MENU_PATH . '/profile') : t('settings profiles'), '!restorelink' => user_access('restore from backup') ? l(t('restore feature'), BACKUP_MIGRATE_MENU_PATH . '/restore') : t('restore feature'), '!phpmyadminurl' => 'http://www.phpmyadmin.net')),
      'access arguments' => array('perform backup'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/restore' => array(
      'title' => t('Restore Tab'),
      'body' => t('Upload a backup and migrate backup file. The restore function will not work with database dumps from other sources such as phpMyAdmin.'),
      'access arguments' => array('restore from backup'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/settings/destination' => array(
      'title' => t('Destinations'),
      'body' => t('Destinations are the places you can save your backup files to or them load from.'),
      'more' => t('Files can be saved to a directory on your web server, downloaded to your desktop or emailed to a specified email account. From the Destinations tab you can create, delete and edit destinations or list the files which have already been backed up to the available destinations.'),
      'access arguments' => array('administer backup and migrate'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/settings/source' => array(
      'title' => t('Sources'),
      'body' => t('Sources are the things that can be backed up such as database or file directories.'),
      'access arguments' => array('administer backup and migrate'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/settings/profile' => array(
      'title' => t('Profiles'),
      'body' => t('Profiles are saved backup settings. Profiles store your table exclusion settings as well as your backup file name, compression and timestamp settings. You can use profiles in !schedulelink and for !manuallink.',
                  array('!schedulelink' => user_access('administer backup and migrate') ? l(t('schedules'), BACKUP_MIGRATE_MENU_PATH . '/schedule') : t('settings profiles'), '!manuallink' => user_access('perform backups') ? l(t('manual backups'), BACKUP_MIGRATE_MENU_PATH) : t('manual backups'))),
      'more' => t('You can create new profiles using the add profiles tab or by checking the "Save these settings" button on the advanced backup page.'),
      'access arguments' => array('administer backup and migrate'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/schedule' => array(
      'title' => t('Scheduling'),
      'body' => t('Automatically backup up your database on a regular schedule using <a href="!cronurl">cron</a>.', 
                  array('!cronurl' => 'http://drupal.org/cron')),
      'more' => t('Each schedule will run a maximum of once per cron run, so they will not run more frequently than your cron is configured to run. If you specify a number of backups to keep for a schedule, old backups will be deleted as new ones created. <strong>If specifiy a number of files to keep other backup files in that schedule\'s destination will get deleted</strong>.'),
      'access arguments' => array('administer backup and migrate'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/settings/import' => array(
      'title' => t('Importing Settings'),
      'body' => t('Import a settings profile, backup schedule, source or destination by pasting the export code into the textarea.', 
                  array('!cronurl' => 'http://drupal.org/cron')),
    ),
  );

  if (isset($help[$section])) {
    return $help[$section]['body'];
  }

  if ($section == 'admin/help#backup_migrate') {
    $out = "";
    foreach ($help as $key => $section) {
      if (isset($section['access arguments'])) {
        foreach($section['access arguments'] as $access) {
          if (!user_access($access)) {
            continue 2;
          }
        }
      }
      if (@$section['title']) {
        if (!is_numeric($key)) {
          $section['title'] = l($section['title'], $key);
        }
        $out .= "<h3>". $section['title'] ."</h3>";
      }
      $out .= "<p>". $section['body'] ."</p>";
      if (!empty($section['more'])) {
        $out .= "<p>". $section['more'] ."</p>";
      }
    }
    return $out;
  }
}

/**
 * Implementation of hook_menu().
 */
function backup_migrate_menu() {
  $items = array();

  $items[BACKUP_MIGRATE_MENU_PATH] = array(
    'title' => 'Backup and Migrate',
    'description' => 'Backup/restore your database or migrate data to or from another Drupal site.',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('', 'backup_migrate_ui_manual_backup_quick', TRUE),
    'access arguments' => array('access backup and migrate'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items[BACKUP_MIGRATE_MENU_PATH . '/export'] = array(
    'title' => 'Backup',
    'description' => 'Backup the database.',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('', 'backup_migrate_ui_manual_backup_quick', TRUE),
    'access arguments' => array('access backup and migrate'),
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items[BACKUP_MIGRATE_MENU_PATH . '/export/quick'] = array(
    'title' => 'Quick Backup',
    'description' => 'Backup the database.',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('', 'backup_migrate_ui_manual_backup_quick', TRUE),
    'access arguments' => array('access backup and migrate'),
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items[BACKUP_MIGRATE_MENU_PATH . '/export/advanced'] = array(
    'title' => 'Advanced Backup',
    'description' => 'Backup the database.',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('', 'backup_migrate_ui_manual_backup_advanced', TRUE),
    'access arguments' => array('perform backup'),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
  );
  $items[BACKUP_MIGRATE_MENU_PATH . '/restore'] = array(
    'title' => 'Restore',
    'description' => 'Restore the database from a previous backup',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('', 'backup_migrate_ui_manual_restore', TRUE),
    'access arguments' => array('restore from backup'),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
  );
  $items[BACKUP_MIGRATE_MENU_PATH . '/backups'] = array(
    'title' => 'Saved Backups',
    'description' => 'Previously created backups',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('', 'backup_migrate_ui_saved_backups', TRUE),
    'access arguments' => array('access backup and migrate'),
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  $items[BACKUP_MIGRATE_MENU_PATH . '/schedule'] = array(
    'title' => 'Schedule',
    'description' => 'Schedule automatic backups',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('', 'backup_migrate_ui_schedule', TRUE),
    'access arguments' => array('administer backup and migrate'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  $items[BACKUP_MIGRATE_MENU_PATH . '/settings'] = array(
    'title' => 'Settings',
    'description' => 'Module settings.',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('crud', 'backup_migrate_crud_ui_list_all', TRUE),
    'access arguments' => array('administer backup and migrate'),
    'weight' => 4,
    'type' => MENU_LOCAL_TASK,
  );
  $items[BACKUP_MIGRATE_MENU_PATH . '/settings/import'] = array(
    'title' => 'Import',
    'description' => 'Import backup and migrate settings.',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('crud', 'backup_migrate_crud_ui_import', TRUE),
    'access arguments' => array('administer backup and migrate'),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
  );

  backup_migrate_include('crud');
  $items += backup_migrate_crud_menu();
  return $items;
}

/**
 * Implementation of hook_cron().
 */
function backup_migrate_elements() {
  $types['backup_migrate_dependent'] = array(
    '#dependencies' => array(),
  );
  return $types;
}

/**
 * Implementation of hook_form_update_script_selection_form_alter().
 */
function backup_migrate_form_update_script_selection_form_alter(&$form, $form_state) {
  // Add a link to backup and migrate.
  $form['backup_migrate'] = array(
    '#type' => 'markup',
    '#weight' => -100,
    '#value' => t('Before you run any database updates, <strong>make sure you have a backup of your database.</strong> Use !backup_migrate to create that backup now.', array('!backup_migrate' => l(t('Backup and Migrate'), BACKUP_MIGRATE_MENU_PATH))),
  );
}

/**
 * Implementation of hook_cron().
 *
 * Takes care of scheduled backups and deletes abandoned temp files.
 */
function backup_migrate_cron() {
  // Backing up requires a full bootstrap as it uses the file functionality in 
  // files.inc. Running poormanscron with caching on can cause cron to run without
  // a full bootstrap so we manually finish bootstrapping here.
  require_once './includes/common.inc';
  _drupal_bootstrap_full();

  // Set the message mode to logging.
  _backup_migrate_message_callback('_backup_migrate_message_log');

  backup_migrate_include('schedules');
  backup_migrate_schedules_cron();

  backup_migrate_include('files');
  _backup_migrate_temp_files_delete();
}

/**
 * Implementation of hook_cron().
 */
function backup_migrate_cronapi($op, $job = NULL) {
  $items = array();
  backup_migrate_include('schedules');
  foreach (backup_migrate_get_schedules() as $schedule) {
    $id = $schedule->get('id');
    $items['backup_migrate_' . $id] = array(
      'description' => t('Run the Backup and Migrate \'!name\' schedule', array('!name' => $schedule->get('name'))),
      'rule' => $schedule->get('cron_schedule'),
      'callback' => 'backup_migrate_schedule_run', 
      'arguments' => array($id),
      'file' => 'includes/schedules.inc',
    );
  }
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function backup_migrate_perm() {
  return array('access backup and migrate', 'perform backup', 'access backup files', 'delete backup files', 'restore from backup', 'administer backup and migrate');
}

/**
 * Implementation of hook_simpletest().
 */
function backup_migrate_simpletest() {
  $dir = drupal_get_path('module', 'backup_migrate') .'/tests';
  $tests = file_scan_directory($dir, '\.test$');
  return array_keys($tests);
}

/**
 * Implementation of hook_theme().
 */
function backup_migrate_theme() {
  $themes = array(
    'backup_migrate_ui_manual_quick_backup_form_inline' => array(
      'arguments' => array('form'),
    ),
    'backup_migrate_ui_quick_schedule_form_inline' => array(
      'arguments' => array('form'),
    ),
    'backup_migrate_dependent' => array(
      'arguments' => array('element'),
    ),
  );
  return $themes;
}


/* Blocks */

/**
 * Implementation of hook_block().
 */
function backup_migrate_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return _backup_migrate_block_info();
    case 'view':
      return _backup_migrate_block_view($delta);
  }
}

/**
 * List the available blocks.
 */
function _backup_migrate_block_info() {
  $blocks = array();
  $blocks['quick_backup'] = array(
    'info' => t('Backup and Migrate Quick Backup'),
    'admin' => TRUE
  );
  return $blocks;
}

/**
 * Show the given block.
 */
function _backup_migrate_block_view($delta) {
  $function = '_backup_migrate_block_view_' . $delta;
  if (function_exists('_backup_migrate_block_view_' . $delta)) {
    return $function();
  }
}

/**
 * Quick Backup block.
 */
function _backup_migrate_block_view_quick_backup() {
  if (user_access('access backup and migrate') && user_access('perform backup')) {
    drupal_add_css(drupal_get_path('module', 'backup_migrate') .'/backup_migrate.css');

    // Messages should be sent to the browser.
    _backup_migrate_message_callback('_backup_migrate_message_browser');
    return array(
      'subject' => t('Quick Backup'),
      'content' => drupal_get_form('backup_migrate_ui_manual_quick_backup_form', FALSE),
    );
  }
  return array();
}

/**
 * Implementation of hook_backup_migrate_destinations().
 */
function backup_migrate_backup_migrate_schedules() {
  backup_migrate_include('sources');

  $sources = backup_migrate_get_sources();

  $schedules = array();
  foreach ($sources as $id => $source) {
    $schedule = array(
      'schedule_id' => $id,
      'name' => $source->get('name'),
      'source_id' => $id,
      'destination_id' => 'scheduled',
      'profile_id' => 'default',
      'period' => variable_get('backup_migrate_default_schedule', 60*60*24),
      'keep' => BACKUP_MIGRATE_SMART_DELETE,
      'enabled' => FALSE,
    );
    $schedules[$id] = backup_migrate_crud_create_item('schedule', $schedule);
  }
  return $schedules;
}


/* Menu Callbacks */

/**
 * A menu callback helper. Handles file includes and interactivity setting.
 */
function backup_migrate_menu_callback($include, $function, $interactive = TRUE) {
  if ($include) {
    backup_migrate_include($include);
  }
  // Set the message handler based on interactivity setting.
  _backup_migrate_message_callback($interactive ? '_backup_migrate_message_browser' : '_backup_migrate_message_log');
  // Get the arguments with the first 3 removed.
  $args = array_slice(func_get_args(), 3);
  return call_user_func_array($function, $args);
}

/**
 * Include views .inc files as necessary.
 */
function backup_migrate_include() {
  static $used = array();
  foreach (func_get_args() as $file) {
    if (!isset($used[$file])) {
      require_once backup_migrate_include_path($file);
    }
  
    $used[$file] = TRUE;
  }
}

/**
 * Include views .inc files as necessary.
 */
function backup_migrate_include_path($file) {
  return './' . drupal_get_path('module', 'backup_migrate') . "/includes/$file.inc";
}


/**
 * The menu callback for easy manual backups.
 */
function backup_migrate_ui_manual_backup_quick() {
  $out = "";
  if (user_access('perform backup')) {
    $out .= drupal_get_form('backup_migrate_ui_manual_quick_backup_form');
  }
  else {
    $out .= t('You do not have permission to back up this site.');
  }
  return $out;
}

/**
 * The menu callback for advanced manual backups.
 */
function backup_migrate_ui_manual_backup_advanced() {
  backup_migrate_include('profiles');
  $out = '';
  $profile_id = arg(BACKUP_MIGRATE_MENU_DEPTH + 2);
  $profile = _backup_migrate_profile_saved_default_profile($profile_id);
  $out .= drupal_get_form('backup_migrate_ui_manual_backup_load_profile_form', $profile);
  $out .= drupal_get_form('backup_migrate_ui_manual_backup_form', $profile);
  return $out;
}

/**
 * The backup/export load profile form.
 */
function backup_migrate_ui_manual_backup_load_profile_form(&$form_state, $profile = NULL) {
  $form = array();
  $profile_options = _backup_migrate_get_profile_form_item_options();
  if (count($profile_options) > 0) {
    $profile_options = array(0 => t('-- Select a Settings Profile --')) + $profile_options;
    $form['profile'] = array(
      "#title" => t("Settings Profile"),
      "#collapsible" => TRUE,
      "#collapsed" => FALSE,
      "#prefix" => '<div class="container-inline">',
      "#suffix" => '</div>',
      "#tree" => FALSE,
      "#description" => t("You can load a profile. Any changes you made below will be lost."),
    );
    $form['profile']['profile_id'] = array(
      "#type" => "select",
      "#title" => t("Load Settings"),
      '#default_value' => is_object($profile) ? $profile->get_id() : 0,
      "#options" => $profile_options,
    );
    $form['profile']['load_profile'] = array(
      '#type' => 'submit',
      '#value' => t('Load Profile'),
    );
  }
  return $form;
}

/**
 * Submit the profile load form.
 */
function backup_migrate_ui_manual_backup_load_profile_form_submit($form, &$form_state) {
  if ($profile = backup_migrate_get_profile($form_state['values']['profile_id'])) {
    variable_set("backup_migrate_profile_id", $profile->get_id());
    $form_state['redirect'] = BACKUP_MIGRATE_MENU_PATH . '/export/advanced';
  }
  else {
    variable_set("backup_migrate_profile_id", NULL);
  }
}

/**
 * The menu callback for quick schedules.
 */
function backup_migrate_ui_schedule() {
  backup_migrate_include('sources', 'schedules', 'profiles');
  $out = '';

  $sources = backup_migrate_get_sources();
  $schedules = backup_migrate_get_schedules();

  $out = drupal_get_form('backup_migrate_ui_schedule_form', $sources, $schedules);
  return $out;
}

/**
 * The quick schedule form.
 */
function backup_migrate_ui_schedule_form(&$form_state, $sources, $schedules) {
  $form = array();

  $form['quickschedule'] = array('#tree' => TRUE);

  // Add a quick schedule item for each source.
  foreach ($sources as $id => $source) {
    if (isset($schedules[$id])) {
      $schedule = $schedules[$id];
      $form['quickschedule'][$id] = array();
      $form['quickschedule'][$id]['#theme'] = 'backup_migrate_ui_quick_schedule_form_inline';
      $form['quickschedule'][$id]['enabled'] = array(
        '#type' => 'checkbox',
        '#title' => t('Automatically backup my !source', array('!source' => $source->get('name'))),
        '#default_value' => $schedule->get('enabled'),
      );
      /*
      $form['quickschedule'][$id]['source_id'] = array(
        '#type' => 'item',
        '#title' => t('Backup Source'),
        '#value' => $source->get('name'),
      );
      */
      $form['quickschedule'][$id]['settings'] = array(
        '#type' => 'backup_migrate_dependent',
        '#dependencies' => array(
          'quickschedule[' . $id . '][enabled]' => TRUE,
        ),
      );
      $options = array(
        (60*60)       => t('Once an hour'),
        (60*60*24)    => t('Once a day'),
        (60*60*24*7)  => t('Once a week'),
      );
      $period = $schedule->get('period');
      if (!isset($options[$period])) {
        $options[$period] = $schedule->get('frequency_description');
      }
      $form['quickschedule'][$id]['settings']['period'] = array(
        '#type' => 'select',
        '#title' => t('Schedule Frequency'),
        '#options' => $options,
        '#default_value' => $period,
      );
      $form['quickschedule'][$id]['settings']['destination_id'] = array(
        '#type' => 'select',
        '#title' => t('Backup Destination'),
        '#options' => _backup_migrate_get_destination_form_item_options('scheduled backup'),
        '#default_value' => $schedule->get('period'),
      );
      $form['quickschedule'][$id]['settings']['profile_id'] = array(
        '#type' => 'select',
        '#title' => t('Settings Profile'),
        '#default_value' => $schedule->get('profile_id'),
        '#options' => _backup_migrate_get_profile_form_item_options(),
      );

      $keep = $schedule->get('keep');
      $option_keys = array_unique(array(BACKUP_MIGRATE_SMART_DELETE, 30, 100, 500, BACKUP_MIGRATE_KEEP_ALL, $keep));
      $options = array();
      foreach ($option_keys as $i) {
        $options[$i] = $schedule->generate_keep_description($i);
      }
      $form['quickschedule'][$id]['settings']['keep'] = array(
        '#type' => 'select',
        '#title' => t('Backup retention'),
        '#options' => $options,
        '#default_value' => $keep,
      );
      $form['quickschedule'][$id]['settings']['advanced'] = array(
        '#type' => 'markup',
        '#value' => l(t('Advanced Settings.'), BACKUP_MIGRATE_MENU_PATH . '/settings/schedule/edit/' . $id, array('query' => drupal_get_destination())),
      );
      // Set the parent for the setttings up a level.
      foreach(element_children($form['quickschedule'][$id]['settings']) as $child) {
        $form['quickschedule'][$id]['settings'][$child]['#parents'] = array('quickschedule', $id, $child);
      }
    }
  }
  if (element_children($form['quickschedule'])) {
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Save Schedules'),
    );
  }
  $form['advanced'] = array(
    '#type' => 'markup',
    '#value' => '<div class="clearblock backup-migrate-footer-message">' . t('For more scheduling options and do add additional schedules, try the <a href="!advancedurl">advanced schedule page</a>.', array('!advancedurl' => url(BACKUP_MIGRATE_MENU_PATH . '/settings/schedule'))) . '</div>',
  );
  return $form;
}

/**
 * Submit the quick schedule form.
 */
function backup_migrate_ui_schedule_form_submit($form, &$form_state) {
  backup_migrate_include('schedules');
  if (user_access('adminsiter backup and migrate')) {
    // Override the backups.
    foreach ($form_state['values']['quickschedule'] as $id => $values) {
      if ($schedule = backup_migrate_get_schedule($id)) {
        $schedule->from_array($values);
        $schedule->save();
      }
    }
  }
}



/**
 * The quick backup form.
 */
function backup_migrate_ui_manual_quick_backup_form(&$form_state, $inline = TRUE) {
  backup_migrate_include('profiles', 'destinations', 'sources');
  drupal_add_js(drupal_get_path('module', 'backup_migrate') .'/backup_migrate.js');

  $form = array();

  // Theme the form if we want it inline.
  if ($inline) {
    $form['#theme'] = 'backup_migrate_ui_manual_quick_backup_form_inline';
  }

  $form['quickbackup'] = array(
    '#type' => 'fieldset',
    "#title" => t("Quick Backup"),
    "#collapsible" => FALSE,
    "#collapsed" => FALSE,
    "#tree" => FALSE,
  );

  $form['quickbackup']['source_id'] = _backup_migrate_get_source_pulldown(variable_get('backup_migrate_source_id', NULL));

  $form['quickbackup']['destination_id'] = array(
    "#type" => "select",
    "#title" => t("Backup Destination"),
    "#options" => _backup_migrate_get_destination_form_item_options('manual backup'),
    "#default_value" => variable_get("backup_migrate_destination_id", "download"),
  );
  $profile_options = _backup_migrate_get_profile_form_item_options();
  $form['quickbackup']['profile_id'] = array(
    "#type" => "select",
    "#title" => t("Settings Profile"),
    '#default_value' => variable_get('backup_migrate_profile_id', NULL),
    "#options" => $profile_options,
  );

  $form['quickbackup']['description'] = array(
    '#type' => 'fieldset',
    "#title" => t("Add a note"),
    "#collapsible" => TRUE,
    "#collapsed" => TRUE,
    "#tree" => FALSE,
  );
  $form['quickbackup']['description']['description'] = array(
    '#type' => 'textarea',
    "#title" => t("Note"),
    '#description' => t('This note will be saved with the backup file and shown on the listing page.'),
  );

  $form['advanced'] = array(
    '#type' => 'markup',
    '#value' => '<div class="clearblock backup-migrate-footer-message">' . t('For more backup options, try the <a href="!advancedurl">advanced backup page</a>.', array('!advancedurl' => url('admin/content/backup_migrate/export/advanced'))) . '</div>',
  );


  $form['quickbackup']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Backup now'),
    '#weight' => 1,
  );

  return $form;
}

/**
 * Validate the quick backup form.
 */
function backup_migrate_ui_manual_quick_backup_form_validate($form, &$form_state) {
  if ($form_state['values']['source_id'] == $form_state['values']['destination_id']) {
    form_set_error('destination_id', t('A source cannot be backed up to itself. Please pick a different destination for this backup.'));
  }
}

/**
 * Submit the quick backup form.
 */
function backup_migrate_ui_manual_quick_backup_form_submit($form, &$form_state) {
  backup_migrate_include('profiles', 'destinations');
  if (user_access('perform backup')) {
    // For a quick backup use the default settings.
    $settings = _backup_migrate_profile_saved_default_profile($form_state['values']['profile_id']);

    // Set the destination to the one chosen in the pulldown.
    $settings->destination_id = $form_state['values']['destination_id'];
    $settings->source_id = $form_state['values']['source_id'];

    // Add the note
    $settings->filters['utils_description'] = $form_state['values']['description'];

    // Save the settings for next time.
    variable_set("backup_migrate_source_id", $form_state['values']['source_id']);
    variable_set("backup_migrate_destination_id", $form_state['values']['destination_id']);
    variable_set("backup_migrate_profile_id", $form_state['values']['profile_id']);

    // Do the backup.
    backup_migrate_ui_manual_backup_perform($settings);
  }
}

/**
 * Theme the quick backup form.
 */
function theme_backup_migrate_ui_manual_quick_backup_form_inline($form) {
  // Remove the titles so that the pulldowns can be displayed inline.
  unset($form['quickbackup']['source_id']['#title']);
  unset($form['quickbackup']['destination_id']['#title']);
  unset($form['quickbackup']['profile_id']['#title']);

  $replacements = array(
    '!from' => drupal_render($form['quickbackup']['source_id']),
    '!to' => drupal_render($form['quickbackup']['destination_id']),
    '!profile' => drupal_render($form['quickbackup']['profile_id']),
    '!submit' => drupal_render($form['quickbackup']['submit']),
  );
  $form['quickbackup']['markup'] = array(
    '#type'   => 'markup',
    "#prefix" => '<div class="container-inline">',
    "#suffix" => '</div>',
    '#value'  => t('Backup from !from to !to using !profile !submit', $replacements),
  );
  unset($form['quickbackup']['source_id']);
  unset($form['quickbackup']['destination_id']);
  unset($form['quickbackup']['profile_id']);
  unset($form['quickbackup']['submit']);
  return drupal_render($form);
}

/**
 * Theme the quick schedule form.
 */
function theme_backup_migrate_ui_quick_schedule_form_inline($form) {
  drupal_add_js(drupal_get_path('module', 'backup_migrate') .'/backup_migrate.js');
  drupal_add_css(drupal_get_path('module', 'backup_migrate') .'/backup_migrate.css');

  // Remove the titles so that the pulldowns can be displayed inline.
  unset($form['settings']['source_id']['#title']);
  unset($form['settings']['period']['#title']);
  unset($form['settings']['destination_id']['#title']);
  unset($form['settings']['profile_id']['#title']);
  unset($form['settings']['keep']['#title']);
  unset($form['settings']['keep']['#field_prefix']);
  unset($form['settings']['keep']['#field_suffix']);

  $replacements = array(
    '!from'       => drupal_render($form['settings']['source_id']),
    '!to'         => drupal_render($form['settings']['destination_id']),
    '!frequency'  => drupal_render($form['settings']['period']),
    '!profile'    => drupal_render($form['settings']['profile_id']),
    '!keep'       => drupal_render($form['settings']['keep']),
  );
  $form['settings'] = array('inline' => array(
    '#type' => 'markup',
    "#prefix" => '<div class="container-inline backup-migrate-quickschedule">',
    "#suffix" => '</div>',
    '#value'  => t('Backup !frequency to !to using !profile keeping !keep', $replacements),
  )) + $form['settings'];
  unset($form['settings']['period']);
  unset($form['settings']['destination_id']);
  unset($form['settings']['profile_id']);
  unset($form['settings']['keep']);
  return drupal_render($form);
}


/**
 * Theme the dependent form section.
 */
function theme_backup_migrate_dependent($element) {
  drupal_add_js(drupal_get_path('module', 'backup_migrate') .'/backup_migrate.js');
  drupal_add_css(drupal_get_path('module', 'backup_migrate') .'/backup_migrate.css');

  $id = form_clean_id(implode('-', $element['#parents']));

  $settings = array(
    'backup_migrate' => array(
      'dependents' => array($id => array('dependent' => $id, 'dependencies' => $element['#dependencies']))
    )
  );
  drupal_add_js($settings, 'setting');

  return '<div id="edit-' . $id . '" class="backup-migrate-form-dependent">' . $element['#children'] . '</div>';
}

/**
 * The backup/export form.
 */
function backup_migrate_ui_manual_backup_form(&$form_state, $profile) {
  drupal_add_js(drupal_get_path('module', 'backup_migrate') .'/backup_migrate.js');

  $form = array();

  $form += _backup_migrate_get_source_form('db');
  $form += _backup_migrate_ui_backup_settings_form($profile);

  $form['profile_id'] = array(
    "#type" => "value",
    '#default_value' => $profile->get_id(),
  );
  $form['storage'] = array(
    "#type" => "value",
    '#default_value' => $profile->storage,
  );
  $form['destination'] = array(
    "#type" => "fieldset",
    "#title" => t("Backup Destination"),
    "#collapsible" => TRUE,
    "#collapsed" => FALSE,
    "#tree" => FALSE,
    "#description" => t("Choose where the backup file will be saved. Backup files contain sensitive data, so be careful where you save them. Select 'Download' to download the file to your desktop."),
    '#weight' => 70,
  );
  $form['destination']['destination_id'] = array(
    "#type" => "select",
    "#title" => t("Destination"),
    "#options" => _backup_migrate_get_destination_form_item_options('manual backup'),
    "#default_value" => variable_get("backup_migrate_destination_id", "download"),
  );
  if (user_access('administer backup and migrate')) {
    $form['destination']['destination_id']['#description'] = l(t("Create new destination"), BACKUP_MIGRATE_MENU_PATH . "/destination/add");
  }

  if (user_access('administer backup and migrate')) {
    $form['save_settings'] = array(
      "#type" => "checkbox",
      "#title" => t('Save these settings.'),
      "#default_value" => FALSE,
      '#weight' => 80,
    );
    $form['save_options'] = array(
      '#type' => 'backup_migrate_dependent',
      '#dependencies' => array(
        'save_settings' => TRUE,
      ),
      '#weight' => 90,
    );
    $name = array(
      '#default_value' => $profile->get('name'),
      '#type' => 'textfield',
      '#title' => t('Save the settings as'),
    );

    if ($profile->get_id()) {
      $form['save_options']['create_new'] = array(
        '#default_value' => $profile->get('name'),
        '#type' => 'radios',
        '#default_value' => 0,
        '#options' => array(
          0 => t("Replace the '%profile' profile", array('%profile' => $profile->get('name'))),
          1 => t('Create new profile'),
        ),
      );

      $name["#title"] = t('Profile name');
      $name["#description"] = t("This will be the name of your new profile if you select 'Create new profile' otherwise it will become the name of the '%profile' profile.", array('%profile' => $profile->get('name')));
    }
    else {
      $name["#title"] = t('Save the settings as');
      $name["#description"] = t('Pick a name for the settings. Your settings will be saved as a profile and will appear in the <a href="!url">Profiles Tab</a>.', array('!url' => url(BACKUP_MIGRATE_MENU_PATH . '/profile')));
      $name["#default_value"] = t('Untitled Profile');
    }
    $form['save_options']['name'] = $name;
    $form['save_options'][] = array(
      '#type' => 'submit',
      '#value' => t('Save Without Backing Up'),
    );
  }
  $form['#validate'][] = 'backup_migrate_ui_manual_quick_backup_form_validate';
  $form['#submit'][] = 'backup_migrate_ui_manual_backup_form_submit';

  $form[] = array(
    '#type' => 'submit',
    '#value' => t('Backup now'),
    '#weight' => 100,
  );
  return $form;
}


/**
 * Submit the form. Save the values as defaults if desired and output the backup file.
 */
function backup_migrate_ui_manual_backup_form_submit($form, &$form_state) {
  // Create a profile with the gien settings.
  $profile = backup_migrate_crud_create_item('profile', $form_state['values']);

  // Save the settings profile if the save box is checked.
  if ($form_state['values']['save_settings'] && user_access('administer backup and migrate')) {
    if (@$form_state['values']['create_new']) {
      // Reset the id and storage so a new item will be saved.
      $profile->set_id(NULL);
      $profile->storage = BACKUP_MIGRATE_STORAGE_NONE;
    }
    $profile->save();
    variable_set("backup_migrate_profile_id", $profile->get_id());
    variable_set("backup_migrate_destination_id", $form_state['values']['destination_id']);
  }

  // Perform the actual backup if that is what was selected.
  if ($form_state['values']['op'] == t('Backup now') && user_access('perform backup')) {
    backup_migrate_ui_manual_backup_perform($profile);
  }
  $form_state['redirect'] = BACKUP_MIGRATE_MENU_PATH . "/export/advanced";
}

/**
 * Perform an actual manual backup and tell the user of the progress.
 */

function backup_migrate_ui_manual_backup_perform($settings) {
  // Peform the actual backup.
  backup_migrate_perform_backup($settings);
}

/**
 * The restore/import upload page.
 */
function backup_migrate_ui_manual_restore() {
  return drupal_get_form('backup_migrate_ui_manual_restore_form');
}

/**
 * The restore/import upload form.
 */
function backup_migrate_ui_manual_restore_form() {
  backup_migrate_include('filters', 'destinations', 'sources');

  drupal_set_message(t('Restoring will delete some or all of your data and cannot be undone. <strong>Always test your backups on a non-production server!</strong>'), 'warning', FALSE);

  $form = array();

  $form['backup_migrate_restore_upload'] = array(
    '#title' => t('Upload a Backup File'),
    '#type' => 'file',
    '#description' => t("Upload a backup file created by this version of this module. For other database backups please use another tool for import. Max file size: %size", array("%size" => format_size(file_upload_max_size()))),
  );

  $sources = _backup_migrate_get_source_form_item_options();
  if (count($sources) > 1) {
    $form['source_id'] = array(
      "#type" => "select",
      "#title" => t("Restore to"),
      "#options" => $sources,
      "#description" => t("Choose the database to restore to. Any database destinations you have created and any databases specified in your settings.php can be restored to."),
      "#default_value" => 'db',
    );
  }
  else {
    $form['source_id'] = array(
      "#type" => "value",
      "#value" => 'db',
    );
  }

  $form = array_merge_recursive($form, backup_migrate_filters_settings_form(backup_migrate_filters_settings_default('restore'), 'restore'));
  // Add the advanced fieldset if there are any fields in it.
  if (@$form['advanced']) {
    $form['advanced']['#type'] = 'fieldset';
    $form['advanced']['#title'] = t('Advanced Options');
    $form['advanced']['#collapsed'] = true;
    $form['advanced']['#collapsible'] = true;
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Restore now'),
  );
  if (user_access('access backup files')) {
    $form[] = array(
      '#type' => 'markup',
      '#value' => t('<p>Or you can restore one of your <a href="!url">previously saved bacups.</a></p>', array("!url" => url("admin/content/backup_migrate/backups"))),
    );
  }
  $form['#attributes'] = array('enctype' => 'multipart/form-data');
  return $form;
}

/**
 * The restore submit. Do the restore.
 */
function backup_migrate_ui_manual_restore_form_submit($form, &$form_state) {
  if ($file = file_save_upload('backup_migrate_restore_upload')) {
    backup_migrate_include('destinations');
    backup_migrate_perform_restore('upload', $file->filepath, $form_state['values']);
  }
  $form_state['redirect'] = BACKUP_MIGRATE_MENU_PATH . '/restore';
}

/**
 * Convert an item to an 'exportable'.
 */
function backup_migrate_ui_export_form(&$form_state, $item) {
  if ($item && function_exists('ctools_var_export')) {
    $code = ctools_var_export($item);
    $form = ctools_export_form($form_state, $code);
    return $form;
  }
  return array();
}

/**
 * List the previously created backups from accross multiple destinations.
 */
function backup_migrate_ui_saved_backups() {
  backup_migrate_include('profiles', 'destinations', 'sources');

  $remote = false;
  $now = $fetch_time = time();
  $out = '';
  $files = array();
  foreach (backup_migrate_get_destinations('list files') as $destination) {
    $label = l($destination->get_name(), BACKUP_MIGRATE_MENU_PATH . '/settings/destination/list/files/' . $destination->get_id());
    $label = '<div class="backup-migrate-destination"><span class="backup-migrate-label">' . t('Location') . ':</span> ' . $label . '</div>';
    $dest_files = $destination->list_files();

    // Refresh the destination
    if (isset($_GET['refresh'])) {
      $destination->file_cache_clear();
    }

    // Get the file fetch time.
    if ($destination->cache_files && $destination->fetch_time) {
      $fetch_time = min($destination->fetch_time, $fetch_time);
    }

    // Add the files from this destination to the full list.
    foreach ($dest_files as $id => $file) {
      $remote = $remote || $file->info('remote');
      $dest_files[$id]->file_info['description'] =  $file->info('description') . $label;
    }
    $files += $dest_files;
  }

  // Redirect if refreshing instead of displaying.
  if (isset($_GET['refresh'])) {
    drupal_goto($_GET['q']);
  }

  // Render the list.
  $out = _backup_migrate_ui_destination_display_file_list($files, 20, TRUE);

  // Add the refesh link if needed.
  if ($fetch_time < $now) {
    $out .= '<div class="description">'. t('This listing was fetched !time ago. !refresh', array('!time' => format_interval($now - $fetch_time, 1), '!refresh' => l(t('fetch now'), $_GET['q'], array('query' => 'refresh=true')))) .'</div>';
  }

  // Add a remote backups warning if there are no remote backups.
  if (!$remote && user_access('administer backup and migrate')) {
      drupal_set_message(t('You do not have any off-site backups. For the highest level of protection, <a href="!addurl">create an off-site destination</a> to save your backups to.', array('!addurl' => url(BACKUP_MIGRATE_MENU_PATH . '/settings/destination/add'))), 'warning', FALSE);
  }

  return $out;
}

/**
 * Perform a backup with the given settings.
 */
function backup_migrate_perform_backup(&$settings) {
  backup_migrate_include('destinations', 'files', 'filters');
  timer_start('backup_migrate_backup');

  // If not in 'safe mode', increase the maximum execution time:
  if (!ini_get('safe_mode') && ini_get('max_execution_time') < 1200) {
    set_time_limit(variable_get('backup_migrate_backup_max_time', 1200));
  }

  // Create the temporary file object to be backed up into.
  $filename = _backup_migrate_construct_filename($settings);
  $file = new backup_file(array('filename' => $filename));
  if (!$file) {
    backup_migrate_backup_fail("Could not run backup because a temporary file could not be created.", array(), $settings);
    return FALSE;
  }

  // Register shutdown callback to deal with timeouts.
  register_shutdown_function('backup_migrate_shutdown', $settings);

  $file = backup_migrate_filters_backup($file, $settings);
  if (!$file) {
    if (_backup_migrate_check_timeout()) {
      backup_migrate_backup_fail('Could not complete the backup because the script timed out. Try increasing your PHP <a href="!url">max_execution_time setting</a>.', array('!url' => 'http://www.php.net/manual/en/info.configuration.php#ini.max-execution-time'), $settings);
    }
    else {
      backup_migrate_backup_fail("Could not complete the backup.", array(), $settings);
    }
    return FALSE;
  }

  $file = backup_migrate_destination_save_file($file, $settings);
  if (!$file) {
    backup_migrate_backup_fail("Could not run backup because the file could not be saved to the destination.", array(), $settings);
    return FALSE;
  }

  // Backup succeeded, 
  $time = timer_stop('backup_migrate_backup');
  $message = '%source backed up successfully to %file in destination %dest in !time. !action';
  $params = array(
    '%file' => $filename,
    '%dest' => $settings->get_destination_name(),
    '%source' => $settings->get_source_name(),
    '!time' => backup_migrate_format_elapsed_time($time['time']),
    '!action' => !empty($settings->performed_action) ? $settings->performed_action : '',
  );
  if (($destination = $settings->get_destination()) && ($links = $destination->get_file_links($file->file_id()))) {
    $params['!links'] = implode(", ", $links);
  }

  backup_migrate_backup_succeed($message, $params, $settings);
  return $file;
}

/**
 * Format an elapsed time given in milleseconds.
 */

function backup_migrate_format_elapsed_time($time) {
  $ms = t('!time ms', array('!time' => $time));
  if ($time < 1000) {
    return $ms;
  }
  return '<abbr title="' . $ms . '">' . format_interval($time / 1000) . '</abbr>';
}

/**
 * Restore from a file in the given destination.
 */
function backup_migrate_perform_restore($destination_id, $file, $settings = array()) {
  backup_migrate_include('files', 'filters');
  timer_start('backup_migrate_restore');

  // If not in 'safe mode', increase the maximum execution time:
  if (!ini_get('safe_mode') && ini_get('max_execution_time') < variable_get('backup_migrate_backup_max_time', 1200)) {
    set_time_limit(variable_get('backup_migrate_restore_max_time', 1200));
  }

  // Make the settings into a default profile.
  if (!is_object($settings)) {
    $settings = backup_migrate_crud_create_item('profile', $settings);
    $settings->source_id = empty($settings->source_id) ? 'db' : $settings->source_id;
  }

  // Register shutdown callback.
  register_shutdown_function('backup_migrate_shutdown', $settings);

  if (!is_object($file)) {
    // Load the file from the destination.
    $file = backup_migrate_destination_get_file($destination_id, $file);
    if (!$file) {
      _backup_migrate_message("Could not restore because the file could not be loaded from the destination.", array(), 'error');
      backup_migrate_cleanup();
      return FALSE;
    }
  }

  // Filter the file and perform the restore.
  $file = backup_migrate_filters_restore($file, $settings);
  if (!$file) {
    if (_backup_migrate_check_timeout()) {
      backup_migrate_restore_fail('Could not perform the restore because the script timed out. Try increasing your PHP <a href="!url">max_execution_time setting</a>.', array('!url' => 'http://www.php.net/manual/en/info.configuration.php#ini.max-execution-time'), 'error');
    }
    else {
      backup_migrate_restore_fail("Could not perform the restore.", array(), 'error');
    }
    backup_migrate_cleanup();
    return FALSE;
  }

  $time = timer_stop('backup_migrate_restore');
  if ($file) {
    $destination = backup_migrate_get_destination($destination_id);
    $message = '%source restored from %dest file %file in !time ms. !action';
    $params = array(
      '%file' => $file->filename(),
      '%source' => $settings->get_source_name(),
      '%dest' => $destination->get_name(),
      '!time' => $time['time'],
      '!action' => !empty($settings->performed_action) ? $settings->performed_action : '',
    );
    if ($destination && $destination->op('list files')) {
      $params['!links'] = t('<a href="!restoreurl">Restore again</a>', array('!restoreurl' => url(BACKUP_MIGRATE_MENU_PATH . '/destination/list/restorefile/'. $destination_id ."/". $file->filename())));
    }
    backup_migrate_restore_succeed($message, $params, $settings);
  }
  // Delete any temp files we've created.
  backup_migrate_cleanup();

  // No errors. Return the file.
  return $file;
}

/**
 * Clean up when a backup operation fails.
 */
function backup_migrate_backup_fail($message, $params, $settings) {
  backup_migrate_include('files', 'filters');

  _backup_migrate_message($message, $params, 'error');
  backup_migrate_cleanup();
  backup_migrate_filters_invoke_all('backup_fail', $settings, $message, $params);
  return FALSE;
}

/**
 * Clean up when a backup operation suceeds.
 */
function backup_migrate_backup_succeed($message, $params, $settings) {
  backup_migrate_include('filters', 'files');
  _backup_migrate_message($message, $params, 'success');
  backup_migrate_cleanup();
  backup_migrate_filters_invoke_all('backup_succeed', $settings, $message, $params);
  return FALSE;
}

/**
 * Clean up when a restore operation fails.
 */
function backup_migrate_restore_fail($message, $params, $settings) {
  backup_migrate_include('files', 'filters');
  _backup_migrate_message($message, $params, 'error');
  backup_migrate_cleanup();
  backup_migrate_filters_invoke_all('restore_fail', $settings, $message, $params);
  return FALSE;
}

/**
 * Clean up when a restore operation suceeds.
 */
function backup_migrate_restore_succeed($message, $params, $settings) {
  backup_migrate_include('filters', 'files');
  _backup_migrate_message($message, $params, 'success');
  backup_migrate_cleanup();
  backup_migrate_filters_invoke_all('restore_succeed', $settings, $message, $params);
  return FALSE;
}


/**
 * Cleanup after a success or failure.
 */
function backup_migrate_cleanup() {
  // Check that the cleanup function exists. If it doesn't then we probably didn't create any files to be cleaned up.
  if (function_exists('_backup_migrate_temp_files_delete')) {
    _backup_migrate_temp_files_delete();
  }
}


/**
 * Shutdown callback. Called when the script terminates even if the script timed out.
 */
function backup_migrate_shutdown($settings) {
  // If we ran out of time, set an error so the user knows what happened
  if (_backup_migrate_check_timeout()) {
    backup_migrate_cleanup();
    backup_migrate_backup_fail('The operation timed out. Try increasing your PHP <a href="!url">max_execution_time setting</a>.', array('!url' => 'http://www.php.net/manual/en/info.configuration.php#ini.max-execution-time'), $settings);
    // The session will have already been written and closed, so we need to write any changes directly.
    sess_write(session_id(), session_encode());
    // Add a redirect or we'll just get whitescreened.
    drupal_goto(BACKUP_MIGRATE_MENU_PATH);
  }
}



/* Actions/Workflow integration */

/**
 * Action to backup the drupal site. Requires actions.module.
function action_backup_migrate_backup($op, $edit = array()) {
  switch ($op) {
    case 'do':
      _backup_migrate_backup_with_defaults();
      watchdog('action', 'Backed up database');
      break;

    case 'metadata':
      return array(
      'description' => t('Backup the database with the default settings'),
      'type' => t('Backup and Migrate'),
      'batchable' => TRUE,
      'configurable' => FALSE,
    );

    // Return an HTML config form for the action.

    case 'form':
      return '';

    // Validate the HTML form.

    case 'validate':
      return TRUE;

    // Process the HTML form to store configuration.

    case 'submit':
      return '';
  }
}
 */

/*
 * Implementation of hook_action_info().
function backup_migrate_action_info() {
  return array(
    'backup_migrate_action_backup' => array(
      '#label' => t('Backup the database'),
      '#module' => t('Backup and Migrate'),
      '#description' => t('Backup the database with the default settings.'),
    ),
  );
}
 */

/*
 * Action callback.
 */
function backup_migrate_action_backup() {
  _backup_migrate_backup_with_defaults();
}

/* Utilities */

/**
 * Backup the database with the default settings.
 */
function _backup_migrate_backup_with_defaults($destination_id = "manual") {
  backup_migrate_include('files', 'profiles');

  $settings = _backup_migrate_profile_saved_default_profile();
  $settings->destination_id = $destination_id;
  $settings->source_id = 'db';
  backup_migrate_perform_backup($settings);
}

/**
 * Helper function to set a drupal message and watchdog message depending on whether the module is being run interactively.
 */
function _backup_migrate_message($message, $replace = array(), $type = 'status') {
  // Only set a message if there is a callback handler to handle the message.
  if (($callback = _backup_migrate_message_callback()) && function_exists($callback)) {
    $callback($message, $replace, $type);
  }

  // Store the message in case it's needed (for the status notification filter for example).
  _backup_migrate_messages($message, $replace, $type);
}

/**
 * Helper function to set a drupal message and watchdog message depending on whether the module is being run interactively.
 */
function _backup_migrate_messages($message = NULL, $replace = array(), $type = 'status') {
  static $messages = array();
  if ($message) {
    $messages[] = array('message' => $message, 'replace' => $replace, 'type' => $type);
  }
  return $messages;
}

/**
 * Send a message to the browser. The normal type of message handling for interactive use.
 */
function _backup_migrate_message_browser($message, $replace, $type) {
  // Log the message as well for admins.
  _backup_migrate_message_log($message, $replace, $type);

  // If there are links, we can display them in the browser.
  if (!empty($replace['!links'])) {
    $message .= " (!links)";
  }
  // Use drupal_set_message to display to the user.
  drupal_set_message(t($message, $replace), str_replace('success', 'status', $type), FALSE);
}

/**
 * Log message if we are in a non-interactive mode such as a cron run.
 */
function _backup_migrate_message_log($message, $replace, $type) {
  // We only want to log the errors or successful completions.
  if (in_array($type, array('error', 'success'))) {
    watchdog('backup_migrate', $message, $replace, $type == 'error' ? WATCHDOG_ERROR : WATCHDOG_NOTICE);
  }
}

/**
 * Set or retrieve a message handler.
 */
function _backup_migrate_message_callback($callback = NULL) {
  static $current_callback = '_backup_migrate_message_log';
  if ($callback !== NULL) {
    $current_callback = $callback;
  }
  return $current_callback;
}

function _backup_migrate_check_timeout() {
  static $timeout;

  // Max execution of 0 means unlimited.
  if (ini_get('max_execution_time') == 0) {
    return false;
  }
  // Figure out when we should stop execution.
  if (!$timeout) {
    $timeout = (!empty($_SERVER['REQUEST_TIME']) ? $_SERVER['REQUEST_TIME'] : time()) + ini_get('max_execution_time') - variable_get('backup_migrate_timeout_buffer', 5);
  }
  return (time() > $timeout);
}

/**
 * Convert an associated array to an ini format string.
 */
function _backup_migrate_array_to_ini($data, $prefix = '') {
  $content = ""; 
  foreach ($data as $key => $val) {
    if ($prefix) {
      $key = $prefix . '[' . $key .']';
    }
    if (is_array($val)) {
      $content .= _backup_migrate_array_to_ini($val, $key);
    }
    else {
      $content .= $key . " = \"". $val ."\"\n";
    }
  }
  return $content;
}

/**
 * Execute a command line command. Returns false if the function failed.
 */
function backup_migrate_exec($command, $args = array()) {
  if (!function_exists('exec') || ini_get('safe_mode')) {
    return FALSE;
  }

  // Escape the arguments
  foreach ($args as $key => $arg) {
    $args[$key] = escapeshellarg($arg);
  }
  $command = strtr($command, $args);
  $output = $result = NULL;

  // Run the command.
  exec($command . ' 2>&1', $output, $result);

  return $result == 0;
}

